-- MySQL Script generated by MySQL Workbench
-- Thu Aug 14 21:28:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Shadow_of_the_sins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Shadow_of_the_sins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shadow_of_the_sins` DEFAULT CHARACTER SET utf8 ;
USE `Shadow_of_the_sins` ;

-- -----------------------------------------------------
-- Table `Shadow_of_the_sins`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shadow_of_the_sins`.`Itens` (
  `idItens` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Passiva` VARCHAR(45) NOT NULL,
  `Ativos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idItens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shadow_of_the_sins`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shadow_of_the_sins`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `funcao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Shadow_of_the_sins`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shadow_of_the_sins`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `idade` INT NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Login_idLogin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Login_idLogin`),
  INDEX `fk_Usuario_Login_idx` (`Login_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Login`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `Shadow_of_the_sins`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
